CREATE TABLE `sys_visitor_appointment` (
  `appointment_id` bigint NOT NULL AUTO_INCREMENT COMMENT '预约ID',
  `visitor_name` varchar(50) NOT NULL COMMENT '访客姓名',
  `visitor_phone` varchar(20) NOT NULL COMMENT '访客手机号',
  `visitor_id_card` varchar(18) DEFAULT NULL COMMENT '访客身份证号',
  `visit_reason` varchar(200) NOT NULL COMMENT '访问事由',
  `dept_id` bigint NOT NULL COMMENT '预约部门ID',
  `dept_name` varchar(50) NOT NULL COMMENT '预约部门名称',
  `contact_user_id` bigint NOT NULL COMMENT '对接人ID',
  `contact_user_name` varchar(50) NOT NULL COMMENT '对接人姓名',
  `start_time` datetime NOT NULL COMMENT '预约开始时间',
  `end_time` datetime NOT NULL COMMENT '预约结束时间',
  `status` char(1) NOT NULL DEFAULT '0' COMMENT '预约状态（0：待确认，1：已确认，2：已拒绝，3：已完成，4：已取消）',
  `reject_reason` varchar(200) DEFAULT NULL COMMENT '拒绝原因',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`appointment_id`),
  KEY `idx_visitor_phone` (`visitor_phone`),
  KEY `idx_dept_id` (`dept_id`),
  KEY `idx_contact_user_id` (`contact_user_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 COMMENT='访客预约登记表';